// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

`timescale 1ns/1ps
module current_control_AXILiteS_s_axi
#(parameter
    C_S_AXI_ADDR_WIDTH = 6,
    C_S_AXI_DATA_WIDTH = 32
)(
    // axi4 lite slave signals
    input  wire                          ACLK,
    input  wire                          ARESET,
    input  wire                          ACLK_EN,
    input  wire [C_S_AXI_ADDR_WIDTH-1:0] AWADDR,
    input  wire                          AWVALID,
    output wire                          AWREADY,
    input  wire [C_S_AXI_DATA_WIDTH-1:0] WDATA,
    input  wire [C_S_AXI_DATA_WIDTH/8-1:0] WSTRB,
    input  wire                          WVALID,
    output wire                          WREADY,
    output wire [1:0]                    BRESP,
    output wire                          BVALID,
    input  wire                          BREADY,
    input  wire [C_S_AXI_ADDR_WIDTH-1:0] ARADDR,
    input  wire                          ARVALID,
    output wire                          ARREADY,
    output wire [C_S_AXI_DATA_WIDTH-1:0] RDATA,
    output wire [1:0]                    RRESP,
    output wire                          RVALID,
    input  wire                          RREADY,
    // user signals
    output wire [0:0]                    rstIntN,
    output wire [0:0]                    ctrlEna,
    output wire [31:0]                   params_Kp,
    output wire [31:0]                   params_Ki2,
    output wire [31:0]                   params_y_max,
    output wire [31:0]                   params_y_min
);
//------------------------Address Info-------------------
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of rstIntN
//        bit 0  - rstIntN[0] (Read/Write)
//        others - reserved
// 0x14 : reserved
// 0x18 : Data signal of ctrlEna
//        bit 0  - ctrlEna[0] (Read/Write)
//        others - reserved
// 0x1c : reserved
// 0x20 : Data signal of params_Kp
//        bit 31~0 - params_Kp[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of params_Ki2
//        bit 31~0 - params_Ki2[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of params_y_max
//        bit 31~0 - params_y_max[31:0] (Read/Write)
// 0x34 : reserved
// 0x38 : Data signal of params_y_min
//        bit 31~0 - params_y_min[31:0] (Read/Write)
// 0x3c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

//------------------------Parameter----------------------
localparam
    ADDR_RSTINTN_DATA_0      = 6'h10,
    ADDR_RSTINTN_CTRL        = 6'h14,
    ADDR_CTRLENA_DATA_0      = 6'h18,
    ADDR_CTRLENA_CTRL        = 6'h1c,
    ADDR_PARAMS_KP_DATA_0    = 6'h20,
    ADDR_PARAMS_KP_CTRL      = 6'h24,
    ADDR_PARAMS_KI2_DATA_0   = 6'h28,
    ADDR_PARAMS_KI2_CTRL     = 6'h2c,
    ADDR_PARAMS_Y_MAX_DATA_0 = 6'h30,
    ADDR_PARAMS_Y_MAX_CTRL   = 6'h34,
    ADDR_PARAMS_Y_MIN_DATA_0 = 6'h38,
    ADDR_PARAMS_Y_MIN_CTRL   = 6'h3c,
    WRIDLE                   = 2'd0,
    WRDATA                   = 2'd1,
    WRRESP                   = 2'd2,
    WRRESET                  = 2'd3,
    RDIDLE                   = 2'd0,
    RDDATA                   = 2'd1,
    RDRESET                  = 2'd2,
    ADDR_BITS         = 6;

//------------------------Local signal-------------------
    reg  [1:0]                    wstate = WRRESET;
    reg  [1:0]                    wnext;
    reg  [ADDR_BITS-1:0]          waddr;
    wire [31:0]                   wmask;
    wire                          aw_hs;
    wire                          w_hs;
    reg  [1:0]                    rstate = RDRESET;
    reg  [1:0]                    rnext;
    reg  [31:0]                   rdata;
    wire                          ar_hs;
    wire [ADDR_BITS-1:0]          raddr;
    // internal registers
    reg  [0:0]                    int_rstIntN = 'b0;
    reg  [0:0]                    int_ctrlEna = 'b0;
    reg  [31:0]                   int_params_Kp = 'b0;
    reg  [31:0]                   int_params_Ki2 = 'b0;
    reg  [31:0]                   int_params_y_max = 'b0;
    reg  [31:0]                   int_params_y_min = 'b0;

//------------------------Instantiation------------------

//------------------------AXI write fsm------------------
assign AWREADY = (wstate == WRIDLE);
assign WREADY  = (wstate == WRDATA);
assign BRESP   = 2'b00;  // OKAY
assign BVALID  = (wstate == WRRESP);
assign wmask   = { {8{WSTRB[3]}}, {8{WSTRB[2]}}, {8{WSTRB[1]}}, {8{WSTRB[0]}} };
assign aw_hs   = AWVALID & AWREADY;
assign w_hs    = WVALID & WREADY;

// wstate
always @(posedge ACLK) begin
    if (ARESET)
        wstate <= WRRESET;
    else if (ACLK_EN)
        wstate <= wnext;
end

// wnext
always @(*) begin
    case (wstate)
        WRIDLE:
            if (AWVALID)
                wnext = WRDATA;
            else
                wnext = WRIDLE;
        WRDATA:
            if (WVALID)
                wnext = WRRESP;
            else
                wnext = WRDATA;
        WRRESP:
            if (BREADY)
                wnext = WRIDLE;
            else
                wnext = WRRESP;
        default:
            wnext = WRIDLE;
    endcase
end

// waddr
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (aw_hs)
            waddr <= AWADDR[ADDR_BITS-1:0];
    end
end

//------------------------AXI read fsm-------------------
assign ARREADY = (rstate == RDIDLE);
assign RDATA   = rdata;
assign RRESP   = 2'b00;  // OKAY
assign RVALID  = (rstate == RDDATA);
assign ar_hs   = ARVALID & ARREADY;
assign raddr   = ARADDR[ADDR_BITS-1:0];

// rstate
always @(posedge ACLK) begin
    if (ARESET)
        rstate <= RDRESET;
    else if (ACLK_EN)
        rstate <= rnext;
end

// rnext
always @(*) begin
    case (rstate)
        RDIDLE:
            if (ARVALID)
                rnext = RDDATA;
            else
                rnext = RDIDLE;
        RDDATA:
            if (RREADY & RVALID)
                rnext = RDIDLE;
            else
                rnext = RDDATA;
        default:
            rnext = RDIDLE;
    endcase
end

// rdata
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (ar_hs) begin
            rdata <= 1'b0;
            case (raddr)
                ADDR_RSTINTN_DATA_0: begin
                    rdata <= int_rstIntN[0:0];
                end
                ADDR_CTRLENA_DATA_0: begin
                    rdata <= int_ctrlEna[0:0];
                end
                ADDR_PARAMS_KP_DATA_0: begin
                    rdata <= int_params_Kp[31:0];
                end
                ADDR_PARAMS_KI2_DATA_0: begin
                    rdata <= int_params_Ki2[31:0];
                end
                ADDR_PARAMS_Y_MAX_DATA_0: begin
                    rdata <= int_params_y_max[31:0];
                end
                ADDR_PARAMS_Y_MIN_DATA_0: begin
                    rdata <= int_params_y_min[31:0];
                end
            endcase
        end
    end
end


//------------------------Register logic-----------------
assign rstIntN      = int_rstIntN;
assign ctrlEna      = int_ctrlEna;
assign params_Kp    = int_params_Kp;
assign params_Ki2   = int_params_Ki2;
assign params_y_max = int_params_y_max;
assign params_y_min = int_params_y_min;
// int_rstIntN[0:0]
always @(posedge ACLK) begin
    if (ARESET)
        int_rstIntN[0:0] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_RSTINTN_DATA_0)
            int_rstIntN[0:0] <= (WDATA[31:0] & wmask) | (int_rstIntN[0:0] & ~wmask);
    end
end

// int_ctrlEna[0:0]
always @(posedge ACLK) begin
    if (ARESET)
        int_ctrlEna[0:0] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_CTRLENA_DATA_0)
            int_ctrlEna[0:0] <= (WDATA[31:0] & wmask) | (int_ctrlEna[0:0] & ~wmask);
    end
end

// int_params_Kp[31:0]
always @(posedge ACLK) begin
    if (ARESET)
        int_params_Kp[31:0] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_PARAMS_KP_DATA_0)
            int_params_Kp[31:0] <= (WDATA[31:0] & wmask) | (int_params_Kp[31:0] & ~wmask);
    end
end

// int_params_Ki2[31:0]
always @(posedge ACLK) begin
    if (ARESET)
        int_params_Ki2[31:0] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_PARAMS_KI2_DATA_0)
            int_params_Ki2[31:0] <= (WDATA[31:0] & wmask) | (int_params_Ki2[31:0] & ~wmask);
    end
end

// int_params_y_max[31:0]
always @(posedge ACLK) begin
    if (ARESET)
        int_params_y_max[31:0] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_PARAMS_Y_MAX_DATA_0)
            int_params_y_max[31:0] <= (WDATA[31:0] & wmask) | (int_params_y_max[31:0] & ~wmask);
    end
end

// int_params_y_min[31:0]
always @(posedge ACLK) begin
    if (ARESET)
        int_params_y_min[31:0] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_PARAMS_Y_MIN_DATA_0)
            int_params_y_min[31:0] <= (WDATA[31:0] & wmask) | (int_params_y_min[31:0] & ~wmask);
    end
end


//------------------------Memory logic-------------------

endmodule
