// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcurrent_control.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCurrent_control_CfgInitialize(XCurrent_control *InstancePtr, XCurrent_control_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCurrent_control_Set_rstIntN(XCurrent_control *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCurrent_control_WriteReg(InstancePtr->Axilites_BaseAddress, XCURRENT_CONTROL_AXILITES_ADDR_RSTINTN_DATA, Data);
}

u32 XCurrent_control_Get_rstIntN(XCurrent_control *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCurrent_control_ReadReg(InstancePtr->Axilites_BaseAddress, XCURRENT_CONTROL_AXILITES_ADDR_RSTINTN_DATA);
    return Data;
}

void XCurrent_control_Set_ctrlEna(XCurrent_control *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCurrent_control_WriteReg(InstancePtr->Axilites_BaseAddress, XCURRENT_CONTROL_AXILITES_ADDR_CTRLENA_DATA, Data);
}

u32 XCurrent_control_Get_ctrlEna(XCurrent_control *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCurrent_control_ReadReg(InstancePtr->Axilites_BaseAddress, XCURRENT_CONTROL_AXILITES_ADDR_CTRLENA_DATA);
    return Data;
}

void XCurrent_control_Set_params_Kp(XCurrent_control *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCurrent_control_WriteReg(InstancePtr->Axilites_BaseAddress, XCURRENT_CONTROL_AXILITES_ADDR_PARAMS_KP_DATA, Data);
}

u32 XCurrent_control_Get_params_Kp(XCurrent_control *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCurrent_control_ReadReg(InstancePtr->Axilites_BaseAddress, XCURRENT_CONTROL_AXILITES_ADDR_PARAMS_KP_DATA);
    return Data;
}

void XCurrent_control_Set_params_Ki2(XCurrent_control *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCurrent_control_WriteReg(InstancePtr->Axilites_BaseAddress, XCURRENT_CONTROL_AXILITES_ADDR_PARAMS_KI2_DATA, Data);
}

u32 XCurrent_control_Get_params_Ki2(XCurrent_control *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCurrent_control_ReadReg(InstancePtr->Axilites_BaseAddress, XCURRENT_CONTROL_AXILITES_ADDR_PARAMS_KI2_DATA);
    return Data;
}

void XCurrent_control_Set_params_y_max(XCurrent_control *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCurrent_control_WriteReg(InstancePtr->Axilites_BaseAddress, XCURRENT_CONTROL_AXILITES_ADDR_PARAMS_Y_MAX_DATA, Data);
}

u32 XCurrent_control_Get_params_y_max(XCurrent_control *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCurrent_control_ReadReg(InstancePtr->Axilites_BaseAddress, XCURRENT_CONTROL_AXILITES_ADDR_PARAMS_Y_MAX_DATA);
    return Data;
}

void XCurrent_control_Set_params_y_min(XCurrent_control *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCurrent_control_WriteReg(InstancePtr->Axilites_BaseAddress, XCURRENT_CONTROL_AXILITES_ADDR_PARAMS_Y_MIN_DATA, Data);
}

u32 XCurrent_control_Get_params_y_min(XCurrent_control *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCurrent_control_ReadReg(InstancePtr->Axilites_BaseAddress, XCURRENT_CONTROL_AXILITES_ADDR_PARAMS_Y_MIN_DATA);
    return Data;
}

