// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xcurrent_control.h"

extern XCurrent_control_Config XCurrent_control_ConfigTable[];

XCurrent_control_Config *XCurrent_control_LookupConfig(u16 DeviceId) {
	XCurrent_control_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCURRENT_CONTROL_NUM_INSTANCES; Index++) {
		if (XCurrent_control_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XCurrent_control_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XCurrent_control_Initialize(XCurrent_control *InstancePtr, u16 DeviceId) {
	XCurrent_control_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XCurrent_control_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XCurrent_control_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

